import React,{useEffect,useState} from 'react';
import http from '../api/http';
import { useAuth } from '../context/AuthContext';

const blank={article_id:'',title:'',description:'',estimated_time:5,questions:[{question:'',explanation:'',options:[{option_text:'',is_correct:true},{option_text:'',is_correct:false}]}]};
export default function QuizManager(){const {user}=useAuth(); const [articles,setArticles]=useState([]);const [form,setForm]=useState(blank);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!user)return;http.get(`/api/articles/user/${user.id}`).then(r=>setArticles(r.data)).catch(()=>setArticles([]));},[]);
 const updateQ=(i,key,val)=>setForm(f=>({...f,questions:f.questions.map((q,j)=>j===i?{...q,[key]:val}:q)}));
 const updateO=(qi,oi,key,val)=>setForm(f=>({...f,questions:f.questions.map((q,j)=>j===qi?{...q,options:q.options.map((o,k)=>k===oi?{...o,[key]:val}:o)}:q)}));
 const addQ=()=>setForm(f=>({...f,questions:[...f.questions,{question:'',explanation:'',options:[{option_text:'',is_correct:true},{option_text:'',is_correct:false}]}]}));
 const save=async e=>{e.preventDefault();setMessage('');setError('');try{await http.post('/api/quizzes',form);setMessage('Quiz saved successfully.');}catch(e){setError(e.response?.data?.message||'Could not save quiz.');}};
 return <div className="container" style={{maxWidth:850}}><h1>Quiz Management</h1><p style={{color:'#666'}}>Create or replace a quiz for one of your published articles.</p><form onSubmit={save}><label>Article</label><select className="select-field" required value={form.article_id} onChange={e=>setForm({...form,article_id:e.target.value})}><option value="">Select article</option>{articles.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><label>Quiz title</label><input className="input-field" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><label>Description</label><textarea className="textarea-field" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{form.questions.map((q,qi)=><div key={qi} style={{background:'white',padding:18,border:'1px solid var(--border-color)',borderRadius:8,margin:'14px 0'}}><h3>Question {qi+1}</h3><input className="input-field" required value={q.question} onChange={e=>updateQ(qi,'question',e.target.value)}/>{q.options.map((o,oi)=><div key={oi} style={{display:'flex',gap:8,alignItems:'center'}}><input className="input-field" required value={o.option_text} placeholder={`Option ${oi+1}`} onChange={e=>updateO(qi,oi,'option_text',e.target.value)}/><label><input type="radio" name={`correct-${qi}`} checked={o.is_correct} onChange={()=>setForm(f=>({...f,questions:f.questions.map((qq,j)=>j===qi?{...qq,options:qq.options.map((oo,k)=>({...oo,is_correct:k===oi}))}:qq)}))}/> Correct</label></div>)}<button type="button" className="btn btn-secondary" onClick={()=>updateQ(qi,'options',[...q.options,{option_text:'',is_correct:false}])}>Add option</button><label>Explanation</label><textarea className="textarea-field" value={q.explanation} onChange={e=>updateQ(qi,'explanation',e.target.value)}/></div>)}{message&&<p style={{color:'#166534'}}>{message}</p>}{error&&<p style={{color:'crimson'}}>{error}</p>}<button type="button" className="btn btn-secondary" onClick={addQ}>Add question</button> <button className="btn btn-primary">Save Quiz</button></form></div>}
