import React,{useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import http from '../api/http';

export default function Quiz(){
 const {id}=useParams(); const nav=useNavigate(); const [quiz,setQuiz]=useState(null); const [answers,setAnswers]=useState({}); const [result,setResult]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{http.get(`/api/quizzes/${id}`).then(r=>setQuiz(r.data)).catch(e=>setError(e.response?.data?.message||'Could not load quiz.')).finally(()=>setLoading(false));},[id]);
 const submit=async()=>{setSubmitting(true);setError('');try{const payload=quiz.questions.map(q=>({question_id:q.id,selected_option_id:answers[q.id]||null}));const r=await http.post(`/api/quizzes/${id}/attempts`,{answers:payload});setResult(r.data);}catch(e){setError(e.response?.data?.message||'Please log in to submit the quiz.');}finally{setSubmitting(false);}};
 if(loading)return <div className="container"><p>Loading quiz...</p></div>; if(error&&!quiz)return <div className="container"><p style={{color:'crimson'}}>{error}</p></div>; if(!quiz)return null;
 return <div className="container" style={{maxWidth:'800px'}}><Link to={`/article/${quiz.article_id}`}>← Back to article</Link><h1>{quiz.title}</h1><p style={{color:'#666'}}>{quiz.description}</p>
 {result?<div><div style={{padding:'24px',background:'white',border:'1px solid var(--border-color)',borderRadius:8,textAlign:'center'}}><h2>Quiz Complete</h2><div style={{fontSize:42,fontWeight:700}}>{result.percentage}%</div><p>{result.score} / {result.total_questions} correct</p><p>{result.percentage>=80?'Excellent work!':result.percentage>=50?'Good effort—review the incorrect answers.':'Keep practicing and try again.'}</p></div><div style={{marginTop:20}}>{quiz.questions.map(q=>{const a=result.answers.find(x=>x.question_id===q.id);return <div key={q.id} style={{background:'white',padding:16,borderRadius:8,border:'1px solid var(--border-color)',marginBottom:12}}><strong>{q.question}</strong><p style={{color:a?.correct?'#166534':'#B91C1C'}}>{a?.correct?'Correct':'Incorrect'}</p>{q.explanation&&<p style={{color:'#666'}}>{q.explanation}</p>}</div>})}</div><button className="btn btn-primary" onClick={()=>{setResult(null);setAnswers({})}}>Retake Quiz</button></div>
 :<><div style={{color:'#666',marginBottom:20}}>Estimated time: {quiz.estimated_time} min · {quiz.questions.length} questions</div>{quiz.questions.map((q,i)=><div key={q.id} style={{background:'white',padding:20,borderRadius:8,border:'1px solid var(--border-color)',marginBottom:14}}><h3>{i+1}. {q.question}</h3>{q.options.map(o=><label key={o.id} style={{display:'block',padding:'9px 0',cursor:'pointer'}}><input type="radio" name={`q-${q.id}`} checked={Number(answers[q.id])===Number(o.id)} onChange={()=>setAnswers(a=>({...a,[q.id]:o.id}))}/> <span style={{marginLeft:8}}>{o.option_text}</span></label>)}</div>)}{error&&<p style={{color:'crimson'}}>{error}</p>}<button className="btn btn-primary" disabled={submitting} onClick={submit}>{submitting?'Submitting...':'Submit Quiz'}</button></>}
 </div>
}
